[[plugin]]
  binary = "buffalo-goth"
  go_get = "github.com/gobuffalo/buffalo-goth"

[[plugin]]
  binary = "buffalo-plugins"
  go_get = "github.com/gobuffalo/buffalo-plugins"

[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop"

[[plugin]]
  binary = "oauth1"
  go_get = "github.com/dghubble/oauth1"

[[plugin]]
  binary = "twitter"
  go_get = "github.com/dghubble/go-twitter/twitter"
